# Site settings
title: BEH-GIS
email: 
description: > # this means to ignore newlines until "baseurl:"
  GIS for the Built Environment and Health Project at Columbia University.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://nygeog.com" # the base hostname & protocol for your site
# twitter_username: nygeog
# github_username:  nygeog

# Build settings
markdown: kramdown
