# Site settings
title: Built Environment and Health Project
email: 
description: > # this means to ignore newlines until "baseurl:"
  Geographic Information Systems (GIS) Group for the <a href="http://beh.columbia.edu"> Built Environment and Health Project</a> at Columbia University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beh-gis.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
