# Site settings
title: BEH-GIS
email: 
description: > # this means to ignore newlines until "baseurl:"
  GIS for the Built Environment and Health Project at Columbia University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beh.columbia.edu" # the base hostname & protocol for your site
twitter_username: 
github_username:  beh-gis

# Build settings
markdown: kramdown
